### ISSUE TITLE
Tajaran, Vulp and Vox scratches are giving me Aided Internal Disorder Sessions.

### ISSUE THREAD

**Issue by SmokingKilz** [AdventDust-Station/DustStation13#8]
Fix pls.

**Comment by Dalekfodder** [comment]
I believe their claws are meant to be stronger as they are claws but I will nerf it down a little

**Comment by SmokingKilz** [comment]
Yeah they're supposed to be stronger, but they like four-five shot at the moment, which is like... wow.

**Comment by Dalekfodder** [comment]
No damage boost, locked
